export function generateClientMotionGuide(projectState) {
  return `# ${projectState.name} - Client Motion Guide

This document outlines the animation strategy for your project. All animations are driven by AnimX, ensuring optimal performance and zero external dependencies.

## Overview
- Project: ${projectState.name}
- Motion Style: ${projectState.motionStyle || 'Default'}

## Sections
${projectState.sections.map(s => `- **${s.type}**: Uses layout and entrance animations to draw focus.`).join('\n')}

*(Auto-generated by AnimX Studio v3.21.0)*
`;
}

export function generateDeveloperGuide(projectState) {
  return `# ${projectState.name} - Developer Implementation Guide

## 1. Load Files
Include these zero-dependency files in your project:
\`\`\`html
<link rel="stylesheet" href="animx.min.css">
<script src="animx.min.js"></script>
\`\`\`

## 2. Usage Examples
**Data Attribute API:**
\`\`\`html
<div data-ax="fade-up" data-ax-duration="600">Animated Content</div>
\`\`\`

**JavaScript API:**
\`\`\`javascript
AnimX.animate('.hero-title', 'text-mask-up');
\`\`\`

## Accessibility & Reduced Motion
AnimX automatically respects \`prefers-reduced-motion: reduce\` OS settings by snapping to final states.

*(Auto-generated by AnimX Studio v3.21.0)*
`;
}

export function generateWordPressGuide(projectState) {
  return `# ${projectState.name} - WordPress Handoff Guide

## 1. Enqueue Scripts
Add the following to your \`functions.php\`:
\`\`\`php
function enqueue_animx_assets() {
    wp_enqueue_style('animx', get_template_directory_uri() . '/assets/animx.min.css', [], '3.21.0');
    wp_enqueue_script('animx', get_template_directory_uri() . '/assets/animx.min.js', [], '3.21.0', true);
}
add_action('wp_enqueue_scripts', 'enqueue_animx_assets');
\`\`\`

## 2. Editor Usage
Use the Gutenberg "Advanced" tab or Elementor "Custom Attributes" to add \`data-ax\` attributes to your blocks.

*(Auto-generated by AnimX Studio v3.21.0)*
`;
}

export function generateWebflowGuide(projectState) {
  return `# ${projectState.name} - Webflow Handoff Guide

## 1. Custom Code Setup
In your Project Settings -> Custom Code:
**Head Code:**
\`\`\`html
<link rel="stylesheet" href="https://your-cdn.com/animx.min.css">
\`\`\`
**Footer Code (Before </body>):**
\`\`\`html
<script src="https://your-cdn.com/animx.min.js"></script>
\`\`\`

## 2. Element Settings
Select an element in Webflow, go to Settings (D), and add a Custom Attribute:
- Name: \`data-ax\`
- Value: \`fade-up\`

*(Auto-generated by AnimX Studio v3.21.0)*
`;
}

export function generateCMSGuide(projectState) {
  return `# ${projectState.name} - CMS Editor Guide

## Adding Animations to Content
When editing content in the CMS, you can apply animation attributes:
- \`data-ax\`: The animation preset (e.g., fade-up)
- \`data-ax-duration\`: Duration in MS
- \`data-ax-stagger\`: Stagger delay in MS

*Tip: Refresh your CMS preview to re-trigger layout animations safely.*

*(Auto-generated by AnimX Studio v3.21.0)*
`;
}

export function generateDeploymentChecklist() {
  return [
    { id: "css-loaded", label: "animx.min.css loaded before page content" },
    { id: "js-loaded", label: "animx.min.js loaded before closing body" },
    { id: "no-errors", label: "No console errors detected" },
    { id: "reduced-motion", label: "Reduced motion verified" },
    { id: "keyboard-focus", label: "Keyboard/focus verified" }
  ];
}

export function escapeHtml(unsafe) {
  if (!unsafe) return '';
  return unsafe
       .replace(/&/g, "&amp;")
       .replace(/</g, "&lt;")
       .replace(/>/g, "&gt;")
       .replace(/"/g, "&quot;")
       .replace(/'/g, "&#039;");
}
