export const ErrorCodes = {
  PRESET_MISSING: 'AX_PRESET_MISSING',
  COMPONENT_PRESET_MISSING: 'AX_COMPONENT_PRESET_MISSING',
  SVG_TARGET_MISSING: 'AX_SVG_TARGET_MISSING',
  PATH_MISSING: 'AX_PATH_MISSING',
  INVALID_ATTRIBUTE: 'AX_INVALID_ATTRIBUTE',
  INVALID_DURATION: 'AX_INVALID_DURATION',
  INVALID_EASE: 'AX_INVALID_EASE',
  INVALID_TRIGGER: 'AX_INVALID_TRIGGER',
  SCROLL_OBSERVER_UNAVAILABLE: 'AX_SCROLL_OBSERVER_UNAVAILABLE',
  TEXT_COMPLEX_HTML: 'AX_TEXT_COMPLEX_HTML',
  TEXT_ALREADY_SPLIT: 'AX_TEXT_ALREADY_SPLIT',
  REDUCED_MOTION_ACTIVE: 'AX_REDUCED_MOTION_ACTIVE',
  CSS_NOT_DETECTED: 'AX_CSS_NOT_DETECTED',
  DUPLICATE_INIT: 'AX_DUPLICATE_INIT',
  EMPTY_TARGET: 'AX_EMPTY_TARGET'
};
